[package]
name = "sample_rs_mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
# mcp_rust_sdk = "0.1.0"
mcp_rust_sdk = { path = "../mcp-rust-sdk" }

tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0"
futures = "0.3"
async-trait = "0.1"
async-stream = "0.3"


# tokio = { version = "1", features = ["full", "io-std"] }
# serde = { version = "1.0", features = ["derive"] }
# anyhow = "1.0"

